### ISSUE TITLE
Search / Filter for zones

### ISSUE THREAD

**Issue by peterschen** [WillyXJ/facileManager#188]
I don't know what the plans are for 2.0 but with the current version a search for zones would be very nice. Managing 200+ zones and spooling through all the pages to find the right zone is clumsy.

Also nice would be to have a quick link to show only zones which need reloading. When I change a zone the menu on the left is annotated with the number of zones which need refreshing. But I have to find the right one by clicking through all the pages (or have 200 records shown on one page - which isn't that nice).

A ajax based filter / search would greatly improve day to day operations.

**Comment by WillyXJ** [comment]
There's no argument the zones page could use a search bar which has been lacking since 1.0.

There's been a lot added to 2.0 and one feature is based on #116 which will give you one button to process all pending changes (zone reloads, server config builds, server upgrades) which will make your operations easier.  However, your idea of a separate view/filter to only show zones in need of attention would offer more flexibility in fmDNS.

Both of these requests might make the 2.0 release - if not, then 2.1.

**Comment by WillyXJ** [comment]
Both features made it into 2.0 - wait for the release.

**Comment by peterschen** [comment]
Awesome!
