### ISSUE TITLE
Question: How to migrate to another server?

### ISSUE THREAD

**Issue by millerc** [WillyXJ/facileManager#209]
I have facile manager installed to manage DNS. I may need to move that installation to another server soon. How do I do that without having to re-enter all the DNS zones and records all over again?

Can I just move the installation as I would any other LAMP based application? I guess the trick is how to force the install to regenerate all the BIND config files?

**Comment by WillyXJ** [comment]
Migrating the fM host should be fairly simple since it's all database-driven and giving specific instructions would be difficult since there are several ways of having the environment (ie dedicated database server (or cluster), multiple web servers, etc.), but the basics would be something like:

1. Backup the database
2. Move the install files (or extract the tarball on the new server)
3. Restore the database
4. Edit config.inc.php on the web server as needed
5. Update /usr/local/facileManager/config.inc.php on the clients if FMHOST changes

If you want to force a server build config, you can either check the box next to the server(s) and select "Build Config" from the bulk actions menu or disable and then enable the server which will reveal the build config button.

If you need more specific answers, please feel free to email support@facilemanager.com.
