### ISSUE TITLE
Feature Request: Ability to switch between HTTP/CRON/SSH 

### ISSUE THREAD

**Issue by Lormen** [WillyXJ/facileManager#261]
I know that if we need to/want to change the way a server connects to the database that we can delete /usr/local/facileManager/config.inc.php and re-run the install but this requires removing the server through the GUI first which, can be, a very long process. Would be nice to be able to simply change the connect method within the GUI, maybe even add fallback methods:
p1:ssh
p2:http

Not sure how much work that would be but I'm sure it's not a 5 second job! :)

**Comment by WillyXJ** [comment]
You shouldn't have to remove the server from the UI.  Just remove the config.inc.php from the client and run the installer again.  Once the client connects to the server, it will pull down the serial and you can set which update method you'd like to use.  The reason it cannot be done through the UI is because the client needs to be setup based on update method (i.e. cronjob, httpd setup, ssh key, etc.).  The only way I can think of supporting this request is to have the client setup httpd, install the ssh key, and define the crontab entry; however, people may not want to run a web server on their DNS servers.

**Comment by Lormen** [comment]
I have done it a couple of times, even defined the serial number in the install and it ended up pulling a different name down so one of them said "Client needs installing" and the other was sitting there with the new details.

I would say that if a server has been set up using SSH and the user wants to change it to HTTP(s) then it would warn the user of the packages needed, once installed it could make the required changes to sudoers (still over SSH).

Then it could run something on the named server letting it know that it now updates over HTTP, maybe... 

I would assume that most people (like myself) would be going from HTTP to SSH rather than the other way round just because of the issues I encountered with SSH as described here: https://github.com/WillyXJ/facileManager/issues/260 

Fallback update methods would still be nice :)

**Comment by WillyXJ** [comment]
After sitting on this request for a few years, I'm sorry, but I don't see how I can provide it.
