### ISSUE TITLE
zone configuration on group of server

### ISSUE THREAD

**Issue by bsturzoiu** [WillyXJ/facileManager#288]
Hello, 
I have problem in creating zone to master/slave configuration.

As you suggest on #279, I create 2 servers, one to be master dns (10.173.35.240)  and the second to be slave dns (10.173.35.252), I group them into a group called testDND, putting server 1 in masters list and serve 2 in slaves list.

Then I create a 2 zones, one for forward and the second for  reverse
For forward zone, I have the following input:
domain name: testnpr.test.net
Template: none
Views: All views
Zone Map: forward
Zone type: master
Clone of (optional) nothing
DNS servers: testDNS

and as additional options:
allow-transfer: 127.0.0.1; 10.173.35.240; 10.173.35.252
allow-update: key "root.test.net", already defined in keys section
also-notify:10.173.35.252
notify: yes

For reverse zone I use:
domain name: 35.173.10.in-addr.arpa
Template: none
Views: all views
Zone-map: reverse
Zone-type: master
Clone of (optional): none
DNS servers: testDNS

and additional options:
allow-transfer: 127.0.0.1; 10.173.35.240; 10.173.35.252
allow-update: key "root.test.net", already defined in keys section
also-notify:10.173.35.252
notify: yes

Using this configuration, in /etc/named/zones/zones.conf.all in slave machine
I have:
zone "testnpr.test.net" {
        type slave;
        file "/etc/named/zones/slave/db.testnpr.test.hosts";
        allow-transfer { 127.0.0.1; 10.173.35.240; 10.173.35.252; };
        allow-update { key "root.test.net"; };
        notify yes;
        masters { 127.0.1.1; };
};
And /etc/named/zones/slave/db.testnpr.test.hosts not exists
If I try to add an additional option for this zone: masters: 10.173.35.240, then the masters is duplicated in the file above and the error is throw.
Similar for reverse zone.

So, what I did wrong?
Thank you in advance.

**Comment by WillyXJ** [comment]
fmDNS attempts to resolve the DNS server names to automatically populate the masters {} option with the proper IP.  It looks like in your case, fmDNS is resolving your master server as 127.0.1.1 instead of 10.173.35.240 and therefore not transferring the zones.  It's a bit of a catch-22 as the DNS server hostnames need to be resolvable in order for the slave to be configured correctly.  You can add your master server and IP to /etc/hosts on your fM web server which should resolve this issue for you.  You may also reference #80 for more information as this has been seen once before.

It seems an alternative method needs to be reviewed and implemented in fmDNS to prevent this confusion in the future.

**Comment by bsturzoiu** [comment]
Thank you, it works,
