### ISSUE TITLE
fmFirewall Load Rules after restart

### ISSUE THREAD

**Issue by air101** [WillyXJ/facileManager#309]
Hi WillyXJ,

is it possible that you include a code that fmFirewall rules are applied after a server restart again? I know I could do this via cron or rc.local but it would be a nice feature :)

Thank you and Best Regards

air

**Comment by WillyXJ** [comment]
EL-based Linux systems get the rules applied at boot already because the rules are stored in /etc/sysconfig/iptables.  This feature request would be for other Linux distros which could get complicated.

Debian-based: Add a script to /etc/network/if-pre-up.d/ to run iptables-restore
Arch: Rules should be stored in /etc/iptables/iptables.rules
SuSE: FW_CUSTOMRULES should be set to fmFirewall.rules in /etc/sysconfig/SuSEfirewall2
Gentoo: Rules should be stored in /var/lib/iptables/rules-save
Slackware: Rules should be stored in /etc/rc.d/rc.firewall

**Comment by WillyXJ** [comment]
fmFirewall already uses the proper file locations for most Linux distros:

```
'iptables' => array(
	'Arch'      => '/etc/iptables/iptables.rules',
	'Fedora'    => '/etc/sysconfig/iptables',
	'Redhat'    => '/etc/sysconfig/iptables',
	'CentOS'    => '/etc/sysconfig/iptables',
	'ClearOS'   => '/etc/sysconfig/iptables',
	'Oracle'    => '/etc/sysconfig/iptables',
	'Gentoo'    => '/var/lib/iptables/rules-save',
	'Slackware' => '/etc/rc.d/rc.firewall'
),
```

The only change I see is to support automatically loading the rules for debian-based systems.

**Comment by WillyXJ** [comment]
v1.3 has been released and contains this fix.
