### ISSUE TITLE
Feature request: support for UTC timezone

### ISSUE THREAD

**Issue by karlism** [WillyXJ/facileManager#318]
Hello,

Can you please add support for UTC and other standard (so called "etc") timezones?
https://en.wikipedia.org/wiki/List_of_tz_database_time_zones

**Comment by WillyXJ** [comment]
I'm not sure what the benefit of using these timezones would be.  Could you please clarify and provide a use case?  The only thing the timezone is used for is to display the Admin Logs within the UI as client's have no way to determine which timezone to use since each fM user can have a different timezone selection.

**Comment by karlism** [comment]
I work for an international company and we have employees from different countries. Using "standard" time-zones like UTC is more convenient in such environments as we don't have to worry about what timezone (or daylight savings) are in specific country at that moment.

**Comment by WillyXJ** [comment]
This is included in fM core 2.2.1.
