### ISSUE TITLE
Undefined index when trying to upgrade

### ISSUE THREAD

**Issue by igorek24** [WillyXJ/facileManager#328]
After uploading new files to the server when i click on upgrade servers in the GUI, I get an error.Here is the errors I get from httpd log file:
`[Fri Jul 08 17:00:06.454598 2016] [:error] [pid 20040] [client ::1:58794] PHP Notice:  Undefined index: username in /var/www/html/fm-init.php on line 115`

`[Fri Jul 08 17:00:06.454673 2016] [:error] [pid 20040] [client ::1:58794] PHP Notice:  Undefined index: password in /var/www/html/fm-init.php on line 11`

The server and a client are on the same server and I was trying to update to 2.2.3 from 2.2.3.

**Comment by WillyXJ** [comment]
Could you please verify the version you were upgrading from?  There is no upgrade path from 2.2.3 to 2.2.3. :)

**Comment by igorek24** [comment]
Sorry, that was my bad. I meant to say 2.2.1 to 2.2.3

**Comment by WillyXJ** [comment]
Could you please confirm you upgraded the web server application before trying to update the client application?  Based on the error you received, it looks like:

1. You were at config-servers.php in your browser
2. Copied the updated files to /var/www/html
3. Selected your client in the browser
4. Clicked the upgrade bulk item

If you performed different steps, please provide them.  If these are the steps you performed, then I see there is a bug since any time the web server app is upgraded, the browser should require to you to reauthenticate in order to go through an upgrade routine.

**Comment by igorek24** [comment]
Here are the steps I've took.
1. Download and extract the complite package.
2. Owerwrite Sserver and the Client files.
3. Update the Database thru the GUI.
4. Selected client in the browser.
5. Clicked the upgrade bulk item (Colored in red).
and that's failing the upgrade with the logs above, also the version number in the top left cornor is still saying v2.2.1

**Comment by WillyXJ** [comment]
Hi,

Could you please provide your environment information?  I have been unable to reproduce this with CentOS 6.8 or 7.2.

Also, the version number listed in the upper left is for facileManager - not the current module in use (i.e. fmDNS).

**Comment by WillyXJ** [comment]
Is this still an issue?
