### ISSUE TITLE
Multiple views can not share the same cache file

### ISSUE THREAD

**Issue by wheelmanstudio** [WillyXJ/facileManager#367]
After an upgrade to 9.10 my bind stopped with a message:
/etc/bind/zones/zones.conf.external:24: writeable file '/etc/bind/zones/slave/db.localhost.hosts': already in use: /etc/bind/zones/zones.conf.saima:29
It is because of two views sharing the same slave zone file. I will just leave it here: [issue details](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=820056)

We need some new zone file generation mechanism for slaves.

**Comment by WillyXJ** [comment]
Thanks for the report.  It should be simple enough to add the domain_id to the filename which is already done for master zones.

**Comment by WillyXJ** [comment]
What version of fmDNS are you using?  I just tested with 2.2.6 and it already supports unique slave file names.

**Comment by WillyXJ** [comment]
Further test scenarios confirmed this bug.  Initial tests were using split-view zones which did not reveal this bug.

fM Version : **2.3.3**
fmDNS Version : **2.2.6**

**Expected Behavior:**
A single zone in multiple views would have unique slave cache files.

**Actual Behavior:**
A single zone in multiple views share the same slave cache file thus generating a bind error:
```
Your named configuration contains one or more errors:/etc/named/zones/zones.conf.External:61: writeable file '/etc/named/zones/slave/db.test-domain.local.hosts': already in use: /etc/named/zones/zones.conf.Internal:78
```

**Steps to reproduce:**
1. Create a server group with one master and at least one slave.
2. Create two or more views
3. Create a zone in "All Views"
4. Build the config on all servers in the group

**Comment by WillyXJ** [comment]
This is now fixed in [the latest beta version](http://www.facilemanager.com/download/?t=4) and later.
