### ISSUE TITLE
[BUG] Unable to connect to MySQL 

### ISSUE THREAD

**Issue by Wild1145** [WillyXJ/facileManager#450]
Replace everything between stars with current version of your facileManager and module installations:  
fM Version : **3.4.2**

**In raising this issue, I confirm the following (please check boxes, eg [X]):**

- [X] I have read and understood the [contributors guide](https://github.com/WillyXJ/facileManager/blob/master/.github/CONTRIBUTING.md).
- [X] I have checked that the bug-fix I am reporting can be replicated, or that the feature I am suggesting isn't already present.
- [X] I have checked that the issue I'm posting isn't already reported.
- [X] I have checked that the issue I'm posting isn't already solved and no duplicates exist in [closed issues](https://github.com/WillyXJ/facileManager/issues?q=is%3Aissue+is%3Aclosed) and [opened issues](https://github.com/WillyXJ/facileManager/issues)
- [X] I have checked the pull requests tab for existing solutions/implementations to my issue/suggestion.

---

**(BUG) Expected Behavior:**
When configuring the MySQL Database, the application is able to connect to the database.

**(BUG) Actual Behavior:**
Regardless of the PHP Version (Tried 7.2 and 7.3), the version of MySQL (Tried both 5.7 and 8.0) the application will not connect to MySQL. Every time it attempts to connect the following errors are thrown:

```
[Wed Jul 24 14:03:44.251663 2019] [php7:notice] [pid 12509] [client 192.168.0.115:33862] PHP Notice:  Undefined variable: __FM_CONFIG in /var/www/html/fm-modules/facileManager/js/facileManager.php on line 302, referer: http://192.168.0.141/fm-install.php?step=2
[Wed Jul 24 14:03:44.251720 2019] [php7:notice] [pid 12509] [client 192.168.0.115:33862] PHP Notice:  Undefined variable: __FM_CONFIG in /var/www/html/fm-modules/facileManager/js/facileManager.php on line 306, referer: http://192.168.0.141/fm-install.php?step=2
[Wed Jul 24 14:03:44.251727 2019] [php7:notice] [pid 12509] [client 192.168.0.115:33862] PHP Notice:  Undefined variable: __FM_CONFIG in /var/www/html/fm-modules/facileManager/js/facileManager.php on line 310, referer: http://192.168.0.141/fm-install.php?step=2
[Wed Jul 24 14:03:44.251794 2019] [php7:error] [pid 12509] [client 192.168.0.115:33862] PHP Fatal error:  Uncaught Error: Call to undefined function buildPopup() in /var/www/html/fm-modules/facileManager/js/facileManager.php:1176\nStack trace:\n#0 {main}\n  thrown in /var/www/html/fm-modules/facileManager/js/facileManager.php on line 1176, referer: http://192.168.0.141/fm-install.php?step=2
[Wed Jul 24 14:03:44.337889 2019] [php7:error] [pid 12509] [client 192.168.0.115:33862] script '/var/www/html/fm-modules/facileManager/js/fm-install.php' not found or unable to stat, referer: http://192.168.0.141/fm-install.php?step=2
```

I have verified that I am able to connect to the database both on the network from the same box as the server, and even through a MySQL Client. I've tried re-installing the entire machine a number of times, but can never get past this. On previous attempts I've manually created the config.inc.php file however the application still is unable to connect to it. 

Every guide I can find doesn't have this issue, and I know the database is working as I can connect as I say, and have had other applications already using the same database server. 

**(BUG) Steps to reproduce:**
Attempting to install the software

**Comment by WillyXJ** [comment]
What do you have for a document root and any rewrite rules?  Your last provided log line is not right as that file should be called from /var/www/html/fm-install.php.

```
script '/var/www/html/fm-modules/facileManager/js/fm-install.php' not found
```

In addition, have you tried installing one of the previous versions in case a bug was introduced in the latest version?
http://www.facilemanager.com/download/facilemanager-complete-3.4.1.tar.gz
http://www.facilemanager.com/download/facilemanager-complete-3.4.tar.gz

**Comment by Wild1145** [comment]
Thanks for the quick response, I haddn't spotted that myself but I guess that makes sense. The document root has the content of the server directory under /var/www/html so I'm installing the server from the root directory of my domain. 

I originally tried installing a much older version by accident but never got this far, I'll try an older release and let you know how things go.

**Comment by Wild1145** [comment]
So I've now tried both the 3.4.1 and 3.4 releases with those download links and I'm getting the same errors. 

I've tried some CHOWN and CHMOD settings to see if it's permissions based for some weird reason and it doesn't appear to be.

**Comment by WillyXJ** [comment]
This is a perplexing one. What's your server environment like (please include full versions and any customizations) so that I can attempt to build one and reproduce this issue?

**Comment by Wild1145** [comment]
For this part of the network there are two VM's on the same network. One for MySQL and one for this. Both machines are CentOS 7, the MySQL one was built on the minimal version and the facileManager one on the Infrastructure server (Though I've also tried the minimal build)

It's MySQL 8.0.16 
The Webserver runs PHP 7.2.20 and has the following installed in YUM:

```
php.x86_64                           7.2.20-1.el7.remi               @remi-php72
php-cli.x86_64                       7.2.20-1.el7.remi               @remi-php72
php-common.x86_64                    7.2.20-1.el7.remi               @remi-php72
php-gd.x86_64                        7.2.20-1.el7.remi               @remi-php72
php-json.x86_64                      7.2.20-1.el7.remi               @remi-php72
php-ldap.x86_64                      7.2.20-1.el7.remi               @remi-php72
php-mysqlnd.x86_64                   7.2.20-1.el7.remi               @remi-php72
php-pdo.x86_64                       7.2.20-1.el7.remi               @remi-php72
php-pecl-mcrypt.x86_64               1.0.2-2.el7.remi.7.2            @remi-php72
php-pecl-zip.x86_64                  1.15.4-1.el7.remi.7.2           @remi-php72
php-process.x86_64                   7.2.20-1.el7.remi               @remi-php72
```

Webserver is 

> CentOS Linux release 7.6.1810 (Core) 

MySQL is 

> CentOS Linux release 7.6.1810 (Core)

Both VM's run on the same physical server that runs ESXI, I've got an OpnSense router that is also the DHCP Authority though again it doesn't look to be a network communication issue as I've been able to prove that the FacileManager server can communicate with my MySQL Server. 

The only customizations were to add the correct Yum repo's to get things like PHP Installed, everything else is just out of the box or just dependency installs like the Apache HTTPD server for example.

**Comment by WillyXJ** [comment]
Ok, similar test environment built and problem was reproduced.  After creating a test file that simply attempts a MySQL authentication and spits out the result, I was getting the following error:

```
The server requested authentication method unknown to the client
```

After some internet searches, I found this solution that fixed it for my test environment.

https://stackoverflow.com/a/52364450

This seems to be something between PHP 7.2+ and MySQL 5.7+.

Or, another method is to set the 'plugin' for the MySQL user to 'mysql_native_password' instead of the default 'caching_sha2_password'.

**Comment by Wild1145** [comment]
So I've made the changes to the MySQL Configuration and re-created the user and I'm still getting the same errors. 

I've also then followed some other guides on creating users to use the older authentication style and it's still giving the same errors. 

I've looked in my MySQL user management through MySQL Workbench and it looks as if the users are all using "Standard" Authentication and not the Sha256 type. I've also tried using the Sha256 option for password auth and I'm getting the exact same error. 

Unless I'm missing something obvious I'm not sure that's the issue in this case?

**Comment by WillyXJ** [comment]
I don't know why it's not working for you.  Here is the script I was using and calling it via the web browser.  If you do the same and the output is "Connected successfully" then this is likely an issue with the fM code that I'll need to dig into further to try reproducing like you've done.  If you get something else then I'd be curious to know if any other PHP/MySQL apps work in your environment.

```
[root@linux-test ~]# cat /var/www/html/test.php 
<?php
$servername = "127.0.0.1";
$username = "myuser";
$password = "mypassword";
// Create connection
$conn = new mysqli($servername, $username, $password);
// Check connection
if ($conn->connect_error) {
    die("Connection failed: " . $conn->connect_error);
} 
echo "Connected successfully";
?>
[root@linux-test ~]# 
```

**Comment by Wild1145** [comment]
Thanks for that, the script is coming back as a permissions error so I am going to take a deeper dive and see if I've missed something. I don't currently have any other PHP apps running in the environment, it's not been something that we've needed before, but do have other applications such as Jira for example that does use MySQL so I know the database it's self is fine, it just seems to be something to do with how PHP is interacting with the Database which is proving to be challenging. 

If I could leave this issue open until I get to the bottom of what's causing the permissions issue that would be ideal, I'm hoping if I can get to the bottom of it and fix that then the original issues I was having should be resolved as well.

**Comment by WillyXJ** [comment]
Cool. Standing by for your update.

**Comment by Dofamin** [comment]
Hello to all!
I have the same problem, I think the error here may be in the php module, since the connection does not work even under the root on the remote machine, and the logs are empty. When I tested this program at work, it worked, here's the guide: https://vk.cc/9FhoAU
After this guide, I slightly changed it, only now I don’t remember what exactly.

**Comment by Dofamin** [comment]
`[Mon Aug 05 02:10:56.015671 2019] [:error] [pid 44984] [client 192.168.0.100:63541] PHP Notice:  Undefined variable: __FM_CONFIG in /var/www/html/server/fm-modules/facileManager/js/facileManager.php on line 302, referer: http://192.168.0.254/fm-install.php?step=2
[Mon Aug 05 02:10:56.015730 2019] [:error] [pid 44984] [client 192.168.0.100:63541] PHP Notice:  Undefined variable: __FM_CONFIG in /var/www/html/server/fm-modules/facileManager/js/facileManager.php on line 306, referer: http://192.168.0.254/fm-install.php?step=2
[Mon Aug 05 02:10:56.015751 2019] [:error] [pid 44984] [client 192.168.0.100:63541] PHP Notice:  Undefined variable: __FM_CONFIG in /var/www/html/server/fm-modules/facileManager/js/facileManager.php on line 310, referer: http://192.168.0.254/fm-install.php?step=2
[Mon Aug 05 02:10:56.015877 2019] [:error] [pid 44984] [client 192.168.0.100:63541] PHP Fatal error:  Call to undefined function buildPopup() in /var/www/html/server/fm-modules/facileManager/js/facileManager.php on line 1176, referer: http://192.168.0.254/fm-install.php?step=2
[Mon Aug 05 02:10:56.114370 2019] [core:error] [pid 44984] [client 192.168.0.100:63541] AH00124: Request exceeded the limit of 10 internal redirects due to probable configuration error. Use 'LimitInternalRecursion' to increase the limit if necessary. Use 'LogLevel debug' to get a backtrace., referer: http://192.168.0.254/fm-install.php?step=2
[Mon Aug 05 02:10:56.164386 2019] [:error] [pid 44985] [client 192.168.0.100:63540] PHP Notice:  Undefined variable: __FM_CONFIG in /var/www/html/server/fm-modules/facileManager/js/facileManager.php on line 302, referer: http://192.168.0.254/fm-install.php?step=2
[Mon Aug 05 02:10:56.164413 2019] [:error] [pid 44985] [client 192.168.0.100:63540] PHP Notice:  Undefined variable: __FM_CONFIG in /var/www/html/server/fm-modules/facileManager/js/facileManager.php on line 306, referer: http://192.168.0.254/fm-install.php?step=2
[Mon Aug 05 02:10:56.164421 2019] [:error] [pid 44985] [client 192.168.0.100:63540] PHP Notice:  Undefined variable: __FM_CONFIG in /var/www/html/server/fm-modules/facileManager/js/facileManager.php on line 310, referer: http://192.168.0.254/fm-install.php?step=2
[Mon Aug 05 02:10:56.164468 2019] [:error] [pid 44985] [client 192.168.0.100:63540] PHP Fatal error:  Call to undefined function buildPopup() in /var/www/html/server/fm-modules/facileManager/js/facileManager.php on line 1176, referer: http://192.168.0.254/fm-install.php?step=2
[Mon Aug 05 02:10:56.166811 2019] [core:error] [pid 44985] [client 192.168.0.100:63540] AH00124: Request exceeded the limit of 10 internal redirects due to probable configuration error. Use 'LimitInternalRecursion' to increase the limit if necessary. Use 'LogLevel debug' to get a backtrace., referer: http://192.168.0.254/fm-install.php?step=2
`

**Comment by Dofamin** [comment]
> Hello to all!
> I have the same problem, I think the error here may be in the php module, since the connection does not work even under the root on the remote machine, and the logs are empty. When I tested this program at work, it worked, here's the guide: [Gide](https://mahedi.me/blog/install-dns-server-with-fmdns-graphical-tool/)
> After this guide, I slightly changed it, only now I don’t remember what exactly.

I realized what was my mistake.
I copied only the server folder, not all the files. :)
Only now, another error appeared, Tested on different browsers.
: Internal Server Error

` [core:error] [pid 50223] [client 192.168.0.100:50498] AH00124: Request exceeded the limit of 10 internal redirects due to probable configuration error. Use 'LimitInternalRecursion' to increase the limit if necessary. Use 'LogLevel debug' to get a backtrace., referer: http://192.168.0.254/
`

**Comment by Wild1145** [comment]
So I've also only ever coppied the content of the server folder to the /var/www/html folder and updated the permissions. What other files should be moved to the web server for the setup?/

**Comment by Wild1145** [comment]
So, I think I've found part of the problem. I did some additional digging, turns out CentOS doesn't allow HTTPD to network connect by default. Following the instructions on here - https://www.digitalocean.com/community/questions/centos-7-warning-mysqli_connect-hy000-2002-permission-denied-in I've managed to use the test script to get a successful connection to the database. 

I'm going to try setting up the fm service now using the database setup as per what I've entered into the test script, but basically if you're running HTTPD on CentOS you'll need to do the following before it will be able to connect to MySQL

`sudo setsebool -P httpd_can_network_connect 1`

Will let you know if that works properly with fm.

**Comment by Wild1145** [comment]
So mixed news. The good news is I've now managed to get it to install which I was the big issue. 

The current issue now is when you login it can't find the admin modules page for some reason, though I'm going to do some more digging and now I know the issue I'm going to re-install from scratch anyway and re-jig things to make it more sensible. If it proves to be an issue when I re-build I'll just raise a separate issue as I can't see it being related to this one. 

Thanks for all your help @WillyXJ - Greatly appreciated :)

**Comment by Dofamin** [comment]
> So mixed news. The good news is I've now managed to get it to install which I was the big issue.
> 
> The current issue now is when you login it can't find the admin modules page for some reason, though I'm going to do some more digging and now I know the issue I'm going to re-install from scratch anyway and re-jig things to make it more sensible. If it proves to be an issue when I re-build I'll just raise a separate issue as I can't see it being related to this one.
> 
> Thanks for all your help @WillyXJ - Greatly appreciated :)

Hello!
There is an error in /var/www/html/server/.htaccess.
Add this string RewriteBase /
right after RewriteEngine On.
It must look like this:

```
<IfModule mod_headers.c>
        <FilesMatch "\.(js|css|txt)$">
                Header set Cache-Control "max-age=7200"
        </FilesMatch>
        <FilesMatch "\.(jpe?g|png|gif|ico)$">
                Header set Cache-Control "max-age=2592000"
        </FilesMatch>
</IfModule>

<IfModule mod_rewrite.c>
RewriteEngine On
RewriteBase /

RewriteCond %{REQUEST_FILENAME} !-d
RewriteCond %{REQUEST_FILENAME} !-f
RewriteRule . index.php [L]
</IfModule>
```
