### ISSUE TITLE
[FEATURE REQUEST] Support for Catalog and RPZ zones.

### ISSUE THREAD

**Issue by dayton967** [WillyXJ/facileManager#471]
I would like to see support for BIND's Catalog and RPZ zones.

For the Catalog zone, the new RR, APL is required which is for a list of IP subnets for Access lists.
For the Catalog zone, you will also require to use SHA1 to generate hashes of the wire format of the domain name.

Both the Catalog and RPZ Zones would require new global or view options to enable these.    This would allow for a simplification of pushing zones.

**Comment by WillyXJ** [comment]
RPZ will be supported in the next release.

I've been reviewing Catalog Zones and I'm not sure I understand how they will benefit fmDNS users since fmDNS can and does create the necessary configuration for slaves once a new master zone is created.  Would you please provide a good use case for having Catalog Zone support built in to fmDNS?

**Comment by WillyXJ** [comment]
Response Policy Zones are now implemented in [fmDNS 4.0-beta1](http://www.facilemanager.com/modules/fmdns/?t=3) and later. Testing is requested. Final release will come out later.

**Comment by WillyXJ** [comment]
[fmDNS 4.0.0](http://www.facilemanager.com/modules/fmdns/) has been released.
