### ISSUE TITLE
ISSUE - PHP 7.3+ Support

### ISSUE THREAD

**Issue by WillyXJ** [WillyXJ/facileManager#492]
fM Version : **3.5.7**
All modules

**In raising this issue, I confirm the following (please check boxes, eg [X]):**

- [X] I have read and understood the [contributors guide](https://github.com/WillyXJ/facileManager/blob/master/.github/CONTRIBUTING.md).
- [X] I have checked that the bug-fix I am reporting can be replicated, or that the feature I am suggesting isn't already present.
- [X] I have checked that the issue I'm posting isn't already reported.
- [X] I have checked that the issue I'm posting isn't already solved and no duplicates exist in [closed issues](https://github.com/WillyXJ/facileManager/issues?q=is%3Aissue+is%3Aclosed) and [opened issues](https://github.com/WillyXJ/facileManager/issues)
- [X] I have checked the pull requests tab for existing solutions/implementations to my issue/suggestion.

---

There have been multiple reports of goofy bugs when using PHP 7.3 or greater. This issue is to track support for PHP 7.3+ for fM and all modules.

**Comment by WillyXJ** [comment]
#459 and #488 are related

**Comment by marksmansj** [comment]
Does 4.0 fix these problems ?

**Comment by WillyXJ** [comment]
No it does not.

**Comment by Dekagold** [comment]
We were doing some long-overdue upgrades the past couple days, so I've got some data to supply in regards to this. For reference server 1 is a DNS server and hosts the web, and server 2 is a DNS server that only has a FM client.

Initially we were on 3.4.1 core and 3.3.3 for the DNS module(as I said, long overdue).  Server 2 was able to be upgraded all the way to 20.04 LTS and PHP 7.4.3 and I was able to change records and add/remove zones without issue.

Upgrading Server 1 to 18.04 LTS and PHP 7.2.24 had no difference, and everything worked as expected still.

Upgrading Server 1 to 20.04 LTS and 7.4.3 after that had no issues with record changes.  If I made a zone change, such as adding/removing a zone, it would take the change successfully on both servers, but threw the error " Server ## does not have php configured properly within httpd or httpd is not running" when the change was applied on both servers. 

After that I rolled back to 18.04/PHP 7.2 and upgraded to the latest FacileManager and fmDNS module.  I tested and made sure everything was still working, then upgraded to 20.04 and PHP 7.4 again.  Results were unchanged - the changes are going through but we're still getting the message above.

Since functionality doesn't seem to be impacted we'll probably stick with this until it can be patched, but I figured this may provide some additional data.  Whatever the issue I'm seeing is, it's tied to either the client not giving the web engine a "success" after it runs, or the web engine not recognizing it. I'm inclined to assume that the issue may lie on the web engine side, since having the client server on PHP 7.4 posed no problems - the message only started happening when we upgraded the one with the web engine on it.

**Comment by WillyXJ** [comment]
I'm finding there aren't any PHP 7.3 or 7.4 compatibility issues yet as cases are turning out to be something else.

@Dekagold I'm assuming both of your fmDNS clients are using http(s) for the update method given the error you receive.  I'm unable to reproduce this with Ubuntu 20.04 server and clients.  What happens when you run the Connection Tests through Admin->Tools?  In addition, what happens when you point your web browser to http://server1/fM/reload.php?

**Comment by Dekagold** [comment]
That is correct - http(s) is being used.  The connection tests come back with "success" for all four tests.  If I go straight to the URL you gave, I get "Incorrect parameters defined."

**Comment by WillyXJ** [comment]
Those are the proper results I expect when everything is working correctly. I’m afraid I have no idea why you get that message during updates after you’ve upgraded your environment.
