### ISSUE TITLE
[FEATURE REQUEST] update same zones on different Views with masters and slaves which are defined as group

### ISSUE THREAD

**Issue by mohsensaeedi** [WillyXJ/facileManager#512]
fM Version : **4.0.2**
fmDNS Version : **4.0.2**

**In raising this issue, I confirm the following :**

- [X] I have read and understood the [contributors guide](https://github.com/WillyXJ/facileManager/blob/master/.github/CONTRIBUTING.md).
- [X] I have checked that the bug-fix I am reporting can be replicated, or that the feature I am suggesting isn't already present.
- [X] I have checked that the issue I'm posting isn't already reported.
- [X] I have checked that the issue I'm posting isn't already solved and no duplicates exist in [closed issues](https://github.com/WillyXJ/facileManager/issues?q=is%3Aissue+is%3Aclosed) and [opened issues](https://github.com/WillyXJ/facileManager/issues)
- [X] I have checked the pull requests tab for existing solutions/implementations to my issue/suggestion.

---

**(BUG | ISSUE) Expected Behavior:**
as you know,  we can use different views on bind (external and internal) to split horizon responses based on client IP source. slave servers should be able to update same zone on different View with same master servers. when we setup Bind without fmdns, it works like a charm, for example we define 192.168.1.1 as example.com master server (for external view) and 192.168.2.1 as example.com master server (for internal view). master servers send zone file based on slaves IP  source. therefore, when slave server send AXFR request as 192.168.1.x, receives example.com in external view and when slave server send AXFR request as 192.168.2.x, receives example.com in internal view. when we use group server in Fmdns, it force slaves zone to use static master IP address (or master's name resolved to IP address). We expect a way to define additional IP address for master servers and use it as alternate master IP address for some zones (for example in Internal views).

If this is a bug (or feature request) different notfiy-sources is required for different view. maybe we can set this item for one master server as zone option. but with more master servers we are unable to define notify-source per master server. is it possible? 

I mean same as this guide [Setting Up a Slave Name Server for a Zone in Multiple Views
](https://flylib.com/books/en/2.684.1/setting_up_a_slave_name_server_for_a_zone_in_multiple_views.html)
**(BUG | ISSUE) Actual Behavior:**
Use predefined master IP address for all zones in any views. because we are using server groups (as #279)
**(BUG | ISSUE) Steps to reproduce:**
We have two masters and two slaves. We have two views which are defined by name Internal and External.
1. Create a server group with two masters and two slaves.
2. Create two views (Internal , External)
3. Create a zone in "External" and a create a zone in "Internal" Views. for example zone name is example.com
4. Build the config on all servers in the group
5. Slaves zones use same master IP address on both Views. 
Obviously, in this case we can not update same zones (with different dns records on different Views). I read various issues about this case And I did not find anything similar.

**Comment by WillyXJ** [comment]
This is a use case that was not thought of during development. This has been changed to a feature request.

**Comment by WillyXJ** [comment]
I'm sorry for the late response here, but while digging into the feature request, I believe this scenario can already be accomplished by using the server overrides for view and zone options.

1. Create a server group with two masters (master1, master2) and two slaves (slave1, slave2).
2. Create two views (Internal , External)
3. Edit the "Additional Options" for each view to define the query-source for "All Servers" which will apply to the masters.
4. Edit the "Additional Options" for each view and select "slave1" from the server drop down to define a different query-source address. Repeat for slave2.
5. Create a zone in "External" and a create a zone in "Internal" Views. for example zone name is example.com
6. Edit the "Additional Options" for each zone to define the transfer-source like you did for the zone query-source.
7. Build the config on all servers in the group
8. Slaves zones use same master IP address on both Views (just like the example link you provided), but the query-source and transfer-source values should be different between the masters and the slaves.

**Comment by oiLvAcciNe** [comment]
Hi,

can we take a look at this?

I am trying to accomplish a view setup in bind.
The answer is ok. Based on the "match-clients" acl that i defined.

But i am having a problem while transferring this to the slave server.
The master refuses the transfer ... to the best of my knowledge this is because there is no key setup for masters on the slave.

![image](https://user-images.githubusercontent.com/93989004/178714386-1a47196a-7bf0-4e5e-896b-6f4095fefa74.png)



if i put a key in the master server i can only download the zone from that view where the key in the allow-transfer

![image](https://user-images.githubusercontent.com/93989004/178733292-ba4651a4-e617-4152-91a1-122fe9d72eb8.png)

![image](https://user-images.githubusercontent.com/93989004/178734267-8e004408-9b96-4ea5-b4ed-94888a5c0773.png)



My fM version on this lab server is v4.3.0
And fmDNS is v5.2.1

![image](https://user-images.githubusercontent.com/93989004/178715848-86d4b940-f2ab-4d0b-9c86-c7f495d6bc2c.png)


I have already tried to to some setup/configuration in fmDNS ... and also this steps provided above ... 

But i'm missing something or this is not possible yet. Can you confirm?



Could we have a entry in the edit view to insert a key value for zone transfer (that would be added to the master ip / key slave zone configurating ?

![image](https://user-images.githubusercontent.com/93989004/178734441-fcf901b7-6405-4753-8478-b496ddf70e64.png)





Regards

**Comment by WillyXJ** [comment]
@oiLvAcciNe Thanks for the report and suggestion of a fix. You are correct in the UI does not currently support your scenario and I will get a commit in for selecting a key for each view.

**Comment by WillyXJ** [comment]
Actually, @oiLvAcciNe you can define multiple keys for a server and then you should be able to limit the transfer based on view like you've done with "allow-transfer."

<img width="497" alt="image" src="https://user-images.githubusercontent.com/1309591/219078688-e6b4d1d2-7d2b-4726-87ad-a360fdc8655f.png">

The only problem is I see the UI allows for multiple keys to be defined on a server, but the configuration that gets built only displays one key.  So, there's still an issue with the code...

**Comment by WillyXJ** [comment]
You can also associate a key with a zone:

<img width="503" alt="image" src="https://user-images.githubusercontent.com/1309591/219084576-50f3a40b-21a4-4c6a-a6e4-4be309f384b3.png">

If you associate your internal and external keys to your server and then associate the keys with their respective views, it might provide the results you are looking for.

**Comment by oiLvAcciNe** [comment]
Hi,
Thanks for looking into this and getting a fix.
.
* About the server keys.
Aldo the syntax allows for multiple keys the current versions of bind does not allow more than one (tested in bind 9.11, 9.16)
.
![image](https://user-images.githubusercontent.com/93989004/220082237-eedc6fe4-65f0-41a3-8288-a516c053793e.png)
.

* Associating keys with the zone.
I does not help, as far as i tested. 
.
.

Have also tested the masters setting
But with this we would need to separate and create different settings per server. (instead of using the name server groups magic)
Its probably possible but not doable... i would need to create a zone master for server1 the a zone slave for server2
(and all diff setting to accomplish this)
.
Regarding this I've seen that if you try to put in masters same server with different keys it only writes the first one.

![image](https://user-images.githubusercontent.com/93989004/220090763-2be63911-6ee3-42a8-bf52-4028fe33554f.png)
![image](https://user-images.githubusercontent.com/93989004/220091096-854a41bb-6b68-4ef1-81c4-43718ad641ac.png)
![image](https://user-images.githubusercontent.com/93989004/220091150-5142f39c-ed73-49d4-b261-40e84e61869b.png)
![image](https://user-images.githubusercontent.com/93989004/220091278-3b21976d-361b-4f4e-acfb-7f33baf50b67.png)


**_(but this is another issue, not totally related with what we are discussing)_** 


.
.
.
The only setting that I've seen working is putting in the slave the line of the master with the key.

![image](https://user-images.githubusercontent.com/93989004/220084015-5f4a1db1-301f-40bd-8320-8d7ea9fd211a.png)


Where to store this key setting? ... we probably could think in putting it in the view settings or in the zone settings.
But the code that generates the conf would needs to have this in consideration... 
(in zone we need to consider the clone zone ... like my case ... where i'm trying to put "same zone" in two views ... same zone but needs different keys)
.
![image](https://user-images.githubusercontent.com/93989004/220085336-d0e1ebbc-725c-46c7-a159-e6389f16805b.png)

.
.
tks
(if a had some time i could try to look to the php code for this, but not right now, so if you can help ... many thanks again).

**Comment by oiLvAcciNe** [comment]
Hey,
Did you have the opportunity to investigate this?

dS

**Comment by WillyXJ** [comment]
I hope to have a solution for this in v6.1.0.

**Comment by WillyXJ** [comment]
Sorry for the delay. This will be implemented in v6.2.0.

![image](https://github.com/user-attachments/assets/63b7c699-4a61-4f46-ade5-cc44984b2aa4)

![image](https://github.com/user-attachments/assets/b8e2c1e1-c0f8-46b5-9202-3f15057f634b)

**Comment by WillyXJ** [comment]
This is now implemented in [fmDNS 6.2.0](https://www.facilemanager.com/modules/fmdns/) and later.
