### ISSUE TITLE
import of existing zones to DB to save command line changes

### ISSUE THREAD

**Issue by empanadadexoubas** [WillyXJ/facileManager#90]
Hello,

I have an environment in which web updates will be made by customers and admins, but console or SSH changes could be done too by admins.
It would be possible to create a programmable task to read all zone files and write its records to database to save manual changes in files with a text editor?
Maybe an adaptation of zoneImportWizard() function?

Thank you for your attention and for this very useful project.

**Comment by WillyXJ** [comment]
I'm going to post-pone this implementation to sort out a more solid method of importing.  Adding new records via fmDNS or CLI would work as an import, but the use case came up of User1 updates a record on the CLI and User2 then updates the same record in fmDNS to a different value - which would be correct and how would fmDNS know?  This is what needs to be sorted out.

**Comment by wispr** [comment]
Jon, I've gone around a few times with this thought too. In our environment, we too have a web portal that our customers can change DNS  and unfortunately we run two separate DNS systems because of that at the moment. You and I had talked about the freeze/thaw options in BIND as it relates to Active Directory. We still cannot integrate our AD environment into this BIND environment because AD uses dynamic zones. If fmdns can use the freeze/thaw command, you could support dynamic zones with AD (yeah for me) but you might be able to use that same logic for zones controlled by multiple endpoints. IE, if a given zone could be updated by customers in a web portal, admins via ssh, and customer support reps via fmns, maybe you set that zone to dynamic in bind, fmdns issues a freeze on it, updates the record, and then thaws it again. You can track all of the changes the fmdns is making to the zone in a changelog for the zone. You'd have to check the serial number on the zone and use it to make sure you aren't reverting.

**Comment by WillyXJ** [comment]
v2.0 will incorporate freeze/thaw during reloads.  Thanks for the suggestion on how to potentially use the logic to fully support this request.  Perhaps it can be included in a minor release.

**Comment by wispr** [comment]
oooohhhh, I'm exited for that. That means we can integrate our AD domain in BIND and use it for actual split horizon! Mostly though, since DNS updates in AD won't actually make it into fmdns, just in bind....

**Comment by peterschen** [comment]
I've tested freeze/thaw some more. In bind the zone file will be updated when dynamic updates are made to the zone. 

When a reload/buildconf is triggered these dynamic changes are essentially gone.

I'm not sure what your ideas are around AD integration so I don't know exactly if this has impact on interoperability with AD integrated DNS.

**Comment by wispr** [comment]
Peter, you're 100% correct. Freeze/thaw is step 1 for dynamic updates with AD. Step 2 is this request, basically sync'ing data from bind into fmdns. I like the idea of defining a "dynamic" zone in fmdns, which can basically mean that other tools are updating the zone files and fmdns needs to update itself first. 

when someone in fmdns clicks on a dynamic zone:
1.)freeze dynamic zone
2.)compares/imports/syncs/whatever existing dynamic zone into its db to ensure up to date copy
3.)thaw
4.)user makes changes in fmdns
5.)when use clicks reload, freeze, commit changes, thaw

**Comment by peterschen** [comment]
I like the idea of having the option to mark a zone dynamic. Th

**Comment by WillyXJ** [comment]
I'm currently working on this feature in the 3.0 development branch.  The easy work has been added to flag a zone with dynamic updates support (checkbox) and now the work to support it is proving to be quite challenging.

From a user-perspective, it seems to make sense to freeze, import zone from one DNS server, and then thaw the zone when a user clicks to edit the zone via the UI.  This way the zone will be fully represented at that time of editing.

However, between the time of zone edits and reloading the zone, more changes could have taken place in the zone file directly via dynamic updates.  So, during a reload, the thaw, compare/update, write, thaw process would have to occur in order to preserve the changes.

Would it make more sense to only perform the compare/update at zone reload time rather than the additional process while editing the zone within the UI leaving the user partially blind to the dynamic zone?  Or perhaps a button at the top of the zone edit page to initiate a zone compare/update?

I'd like to see what some of you (users) think so any feedback/ideas you have would be most appreciated and helpful in determining the direction of this feature development.

**Comment by wispr** [comment]
Yeah, maybe a button to launch the compare/update might be a good way to
go. Or maybe that process is launched when a user tries to edit a zone.

User clicks edit, the zone is compared/updated, and the zone is then
displayed to the user. User makes their changes, hits submit, and a
compare/update is done again.


Robbie Wright
Siuslaw Broadband <https://siuslawbroadband.com>
541-902-5101

**Comment by WillyXJ** [comment]
This is now included in [3.0-alpha1](http://www.facilemanager.com/download/?t=4) and later.  More testing required.

**Comment by WillyXJ** [comment]
Has anybody been able to test this feature in the 3.0-alpha releases?  It's such a big change that I'd like some feedback prior to the stable release.

**Comment by WillyXJ** [comment]
This is now included in [3.0](http://www.facilemanager.com/download/) and later.
